config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'task/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |t| %>
  <div class="container-input-title d-flex justify-content-between">
    <div class="title-label">
      <%= t.label :Tarefa %>
    </div>
    <div class="input-data">
      <%= t.text_field :title %>
    </div>
  </div>
  <br>
  <div class="container-input-title d-flex justify-content-between">
    <div class="details-label">
      <%= t.label :Detalhe %>
    </div>
    <div class="input-data">
      <%= t.text_field :details %>
    </div>

    <% unless t.object.new_record? %>
      <%= t.check_box :completed %> completed
    <% end %>
    
  </div>
  <br>
  <div class="d-flex justify-content-center">
    <%= t.submit class: "btn btn-primary "%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for (@task) do |t| %>
  <div class="container total">
    <div class="container-input-title d-flex justify-content-between my-3">
      <div class="title-label mr-3">
        <%= t.label :Tarefa %>
      </div>
      <div class="input-data">
        <%= t.text_field :title %>
      </div>
    </div>

    <div class="container-input-details d-flex justify-content-between">
      <div class="details-label">
        <%= t.label :Detalhe %>
      </div>
      <div class="details-input">
        <%= t.text_field :details %>
      </div>
    </div>
    <div class="check-completed d-flex justify-content-center align-items-center my-3">
      <% unless t.object.new_record? %>
        <%= t.check_box :completed, class: "mr-3" %> completed 
      <% end %>
    </div>
    <div class="enviar d-flex justify-content-center">
      <%= t.submit class: "btn btn-primary" %>
    </div>
  </div>  
<% end %>

app/views/tasks/index.html.erb
<div class="container d-flex justify-content-start align-items-center flex-column">
  <div class="d-flex justify-content-center align-items-center flex-column">
    <% @tasks.each do |task| %>
      <ul>
        <li>
          <% if task.completed == false %>
            <i class="far fa-square"></i>
          <% else %>
            <i class="fas fa-check-square"></i>
          <% end %>
          <%= link_to task.title, task_path(task), class: "text-decoration-none" %> | 
          <%= link_to '', delete_path(task), method: :delete, data: { confirm: 'Are you sure?' }, :class => "fas fa-trash-alt" %>
        </li>
      </ul>
    <% end  %>

    <%= link_to 'Criar nova tarefa', new_task_path, :class => 'btn btn-primary create-task' %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container d-flex justify-content-start align-items-center flex-column mt-3">
  <%= render 'form', task: @task %>
</div>

app/views/tasks/show.html.erb
<% task = Task.find(params[:id]) %>

<h1 class='text-center'><%= task.title %></h1>
<h3 class='text-center'><%= task.details %></h3>

<div class="d-flex justify-content-center mt-5">
  <%= link_to 'Editar tarefa', edit_task_path, :class => "text-decoration-none pr-3 btn btn-primary" %>
  <br><%= link_to '', tasks_path, :class => "fas fa-undo-alt text-decoration-none ml-3 mr-3 pt-3" %>
  <%= link_to '', delete_path(task), method: :delete, data: { confirm: 'Are you sure?' }, :class => "fas fa-trash-alt pt-3" %>
</div>